

import copy

import astropy.constants as const
import astropy.units as u


PLANET_TEMPLATES = {
    # -------------------------------------------------------------------------
    # Rocky / terrestrial templates
    # -------------------------------------------------------------------------
    "mercury_like": {
        "label": "Mercury-like rocky planet",
        "category": "rocky",
        "radius": 0.383 * const.R_earth,
        "mass": 0.055 * const.M_earth,
        "T": 440 * u.K,
        "mu": 23.0 * u.dimensionless_unscaled,
        "P0": 1.0e-9 * u.bar,
        "composition": {
            "H I": 0.18,
            "He I": 0.05,
            "O I": 0.34,
            "Na I": 0.22,
            "K I": 0.01,
            "NaCl": 0.06,
            "SiO": 0.08,
            "O2": 0.06,
        },
        "notes": "Na-rich, tenuous rocky exosphere inspired by Mercury.",
    },
    "earth_like": {
        "label": "Earth-like rocky planet",
        "category": "rocky",
        "radius": 1.0 * const.R_earth,
        "mass": 1.0 * const.M_earth,
        "T": 288 * u.K,
        "mu": 28.97 * u.dimensionless_unscaled,
        "P0": 1.0 * u.bar,
        "composition": {
            "N I": 0.35,
            "O I": 0.10,
            "He I": 5.0e-6,
            "H I": 5.0e-7,
            "Na I": 1e-9,
            "K I": 1e-10,
            "N2": 0.42,
            "O2": 0.11,
            "H2O": 0.008,
            "CO2": 0.012,
        },
        "notes": "Secondary atmosphere, Earth-like reference case.",
    },
    "mars_like": {
        "label": "Mars-like rocky planet",
        "category": "rocky",
        "radius": 0.532 * const.R_earth,
        "mass": 0.107 * const.M_earth,
        "T": 210 * u.K,
        "mu": 43.0 * u.dimensionless_unscaled,
        "P0": 6.0e-3 * u.bar,
        "composition": {
            "N I": 0.010,
            "O I": 0.004,
            "He I": 1e-5,
            "H I": 1e-6,
            "CO2": 0.93,
            "CO": 0.035,
            "O2": 0.008,
            "H2O": 0.003,
        },
        "notes": "Thin CO2-dominated secondary atmosphere approximated by large mean molecular weight.",
    },
    "super_earth_rocky": {
        "label": "Super-Earth rocky planet",
        "category": "rocky",
        "radius": 1.7 * const.R_earth,
        "mass": 5.0 * const.M_earth,
        "T": 700 * u.K,
        "mu": 30.0 * u.dimensionless_unscaled,
        "P0": 1.0e-2 * u.bar,
        "composition": {
            "O I": 0.18,
            "N I": 0.12,
            "Na I": 0.06,
            "K I": 0.03,
            "H I": 0.01,
            "CO2": 0.32,
            "SO2": 0.12,
            "CO": 0.08,
            "H2O": 0.05,
            "SiO": 0.03,
        },
        "notes": "Generic hot rocky super-Earth with a heavy secondary atmosphere.",
    },
    "lava_world": {
        "label": "Lava world",
        "category": "rocky",
        "radius": 1.9 * const.R_earth,
        "mass": 8.0 * const.M_earth,
        "T": 2200 * u.K,
        "mu": 35.0 * u.dimensionless_unscaled,
        "P0": 1.0e-3 * u.bar,
        "composition": {
            "O I": 0.18,
            "Na I": 0.16,
            "K I": 0.06,
            "Si I": 0.10,
            "Ca I": 0.06,
            "SiO": 0.22,
            "NaCl": 0.10,
            "O2": 0.06,
            "SO2": 0.06,
        },
        "notes": "Generic silicate-vapor / alkali-rich ultra-hot rocky planet.",
    },

    "volatile_super_earth": {
        "label": "Volatile-rich hot super-Earth",
        "category": "rocky",
        "radius": 2.2 * const.R_earth,
        "mass": 6.5 * const.M_earth,
        "T": 900 * u.K,
        "mu": 6.0 * u.dimensionless_unscaled,
        "P0": 5.0e-4 * u.bar,
        "composition": {
            "H I": 0.10,
            "He I": 0.03,
            "O I": 0.04,
            "Na I": 0.01,
            "K I": 0.005,
            "H2": 0.32,
            "H2O": 0.18,
            "CO": 0.12,
            "CO2": 0.08,
            "NO": 0.03,
            "CH4": 0.025,
            "NH3": 0.02,
        },
        "notes": "Transitional hot super-Earth with a volatile-rich, partially retained light envelope.",
    },

    # -------------------------------------------------------------------------
    # Sub-Neptunes / mini-Neptunes / Neptunes
    # -------------------------------------------------------------------------
    "mini_neptune_cool": {
        "label": "Cool mini-Neptune",
        "category": "mini_neptune",
        "radius": 2.3 * const.R_earth,
        "mass": 7.0 * const.M_earth,
        "T": 400 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-4 * u.bar,
        "composition": {
            "H I": 0.46,
            "He I": 0.12,
            "O I": 0.004,
            "Na I": 2e-4,
            "K I": 2e-5,
            "H2": 0.28,
            "H2O": 0.06,
            "CH4": 0.04,
            "NH3": 0.02,
            "CO": 0.015,
        },
        "notes": "H/He-dominated mini-Neptune with trace heavy species.",
    },
    "mini_neptune_warm": {
        "label": "Warm mini-Neptune",
        "category": "mini_neptune",
        "radius": 2.7 * const.R_earth,
        "mass": 9.0 * const.M_earth,
        "T": 700 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-4 * u.bar,
        "composition": {
            "H I": 0.42,
            "He I": 0.11,
            "O I": 0.008,
            "Na I": 3e-4,
            "K I": 3e-5,
            "H2": 0.25,
            "H2O": 0.08,
            "CO": 0.05,
            "CO2": 0.03,
            "CH4": 0.03,
        },
        "notes": "Warm mini-Neptune appropriate for irradiation studies.",
    },
    "sub_neptune": {
        "label": "Sub-Neptune",
        "category": "sub_neptune",
        "radius": 3.4 * const.R_earth,
        "mass": 12.0 * const.M_earth,
        "T": 850 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-4 * u.bar,
        "composition": {
            "H I": 0.44,
            "He I": 0.11,
            "O I": 0.004,
            "Na I": 3e-4,
            "K I": 3e-5,
            "H2": 0.23,
            "H2O": 0.08,
            "CO": 0.06,
            "CO2": 0.03,
            "CH4": 0.025,
            "NH3": 0.02,
        },
        "notes": "Generic irradiated sub-Neptune with H/He envelope.",
    },
    "warm_neptune": {
        "label": "Warm Neptune",
        "category": "neptune",
        "radius": 4.0 * const.R_earth,
        "mass": 17.0 * const.M_earth,
        "T": 900 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-4 * u.bar,
        "composition": {
            "H I": 0.45,
            "He I": 0.10,
            "O I": 0.004,
            "Na I": 3e-4,
            "K I": 3e-5,
            "H2": 0.21,
            "H2O": 0.09,
            "CO": 0.07,
            "CO2": 0.03,
            "NO": 0.005,
            "CH4": 0.015,
        },
        "notes": "Representative warm Neptune atmosphere.",
    },
    "hot_neptune": {
        "label": "Hot Neptune",
        "category": "neptune",
        "radius": 4.3 * const.R_earth,
        "mass": 20.0 * const.M_earth,
        "T": 1200 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-4 * u.bar,
        "composition": {
            "H I": 0.46,
            "He I": 0.09,
            "O I": 0.006,
            "Na I": 4.0e-4,
            "K I": 4.0e-5,
            "H2": 0.18,
            "H2O": 0.10,
            "CO": 0.10,
            "CO2": 0.025,
            "NO": 0.01,
        },
        "notes": "Hot Neptune with stronger heavy-species signature.",
    },

    "super_puff": {
        "label": "Super-puff sub-Neptune",
        "category": "sub_neptune",
        "radius": 6.5 * const.R_earth,
        "mass": 4.5 * const.M_earth,
        "T": 650 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-4 * u.bar,
        "composition": {
            "H I": 0.44,
            "He I": 0.10,
            "O I": 0.003,
            "Na I": 2.0e-4,
            "K I": 2.0e-5,
            "H2": 0.26,
            "H2O": 0.08,
            "CO": 0.05,
            "CO2": 0.02,
            "CH4": 0.03,
            "NH3": 0.02,
        },
        "notes": "Very low-gravity inflated sub-Neptune / super-puff for escape sensitivity tests.",
    },

    # -------------------------------------------------------------------------
    # Gas giants
    # -------------------------------------------------------------------------
    "cold_jupiter": {
        "label": "Cold Jupiter",
        "category": "gas_giant",
        "radius": 1.0 * const.R_jup,
        "mass": 1.1 * const.M_jup,
        "T": 180 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-3 * u.bar,
        "composition": {
            "H I": 0.48,
            "He I": 0.11,
            "O I": 1e-4,
            "Na I": 5e-6,
            "K I": 5e-7,
            "H2": 0.31,
            "CH4": 0.04,
            "NH3": 0.025,
            "H2O": 0.015,
            "CO": 0.005,
            "PH3": 0.01,
        },
        "notes": "Cold giant baseline with weak irradiation and molecule-rich atmosphere.",
    },
    "warm_jupiter": {
        "label": "Warm Jupiter",
        "category": "gas_giant",
        "radius": 1.0 * const.R_jup,
        "mass": 1.0 * const.M_jup,
        "T": 600 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-3 * u.bar,
        "composition": {
            "H I": 0.54,
            "He I": 0.10,
            "O I": 3e-4,
            "Na I": 2e-5,
            "K I": 2e-6,
            "H2": 0.28,
            "H2O": 0.03,
            "CH4": 0.02,
            "CO": 0.015,
            "NH3": 0.01,
        },
        "notes": "Generic warm Jupiter.",
    },
    "hot_jupiter": {
        "label": "Hot Jupiter",
        "category": "gas_giant",
        "radius": 1.2 * const.R_jup,
        "mass": 0.9 * const.M_jup,
        "T": 1400 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-3 * u.bar,
        "composition": {
            "H I": 0.56,
            "He I": 0.09,
            "O I": 4e-4,
            "Na I": 4e-5,
            "K I": 4e-6,
            "H2": 0.22,
            "H2O": 0.06,
            "CO": 0.05,
            "CO2": 0.005,
            "NO": 0.01,
            "OH": 0.005,
        },
        "notes": "Representative hot Jupiter for irradiation studies.",
    },
    "inflated_hot_jupiter": {
        "label": "Inflated hot Jupiter",
        "category": "gas_giant",
        "radius": 1.6 * const.R_jup,
        "mass": 0.6 * const.M_jup,
        "T": 1700 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-3 * u.bar,
        "composition": {
            "H I": 0.58,
            "He I": 0.08,
            "O I": 5e-4,
            "Na I": 6e-5,
            "K I": 6e-6,
            "H2": 0.18,
            "H2O": 0.07,
            "CO": 0.06,
            "CO2": 0.005,
            "NO": 0.012,
            "OH": 0.008,
        },
        "notes": "Low-gravity inflated hot Jupiter.",
    },
    "ultra_hot_jupiter": {
        "label": "Ultra-hot Jupiter",
        "category": "gas_giant",
        "radius": 1.75 * const.R_jup,
        "mass": 1.2 * const.M_jup,
        "T": 2500 * u.K,
        "mu": 2.3 * u.dimensionless_unscaled,
        "P0": 1.0e-3 * u.bar,
        "composition": {
            "H I": 0.62,
            "He I": 0.07,
            "He II": 0.01,
            "O I": 0.010,
            "O II": 0.002,
            "Na I": 5.0e-4,
            "Na II": 1.5e-4,
            "K I": 5.0e-5,
            "K II": 1.5e-5,
            "H2": 0.10,
            "CO": 0.10,
            "H2O": 0.04,
            "NO": 0.02,
            "OH": 0.01,
        },
        "notes": "Ultra-hot giant with partial ionization and strong heavy-species signatures.",
    },

    # -------------------------------------------------------------------------
    # Optional composition-specialized templates
    # -------------------------------------------------------------------------
    "alkali_exosphere_rocky": {
        "label": "Alkali-rich rocky exosphere",
        "category": "rocky",
        "radius": 0.8 * const.R_earth,
        "mass": 0.4 * const.M_earth,
        "T": 1200 * u.K,
        "mu": 25.0 * u.dimensionless_unscaled,
        "P0": 1.0e-8 * u.bar,
        "composition": {
            "Na I": 0.40,
            "K I": 0.08,
            "O I": 0.14,
            "H I": 0.03,
            "He I": 0.03,
            "NaCl": 0.15,
            "SiO": 0.08,
            "SO2": 0.05,
            "O2": 0.04,
        },
        "notes": "Useful for emphasizing Na/K radiation-pressure signatures.",
    },
    "metal_rich_secondary": {
        "label": "Metal-rich secondary atmosphere",
        "category": "rocky",
        "radius": 2.0 * const.R_earth,
        "mass": 6.0 * const.M_earth,
        "T": 1000 * u.K,
        "mu": 35.0 * u.dimensionless_unscaled,
        "P0": 1.0e-2 * u.bar,
        "composition": {
            "O I": 0.16,
            "N I": 0.08,
            "Na I": 0.05,
            "K I": 0.025,
            "CO": 0.18,
            "NO": 0.07,
            "CO2": 0.24,
            "SO2": 0.10,
            "H2O": 0.06,
            "SiO": 0.035,
        },
        "notes": "Heavy secondary atmosphere for parameter studies beyond H/He envelopes.",
    },
}


def get_planet_template(name):
    if name not in PLANET_TEMPLATES:
        available = ", ".join(sorted(PLANET_TEMPLATES.keys()))
        raise KeyError(f"Unknown planet template '{name}'. Available templates: {available}")
    return copy.deepcopy(PLANET_TEMPLATES[name])


def list_planet_templates():
    return sorted(PLANET_TEMPLATES.keys())
