import pathlib
import sys
from typing import Any, Dict

sys.path.append(str(pathlib.Path(__file__).resolve().parents[2]))

import project_func.plot_by_txt_file as plot_txt


# -----------------------------------------------------------------------------
# User settings
# -----------------------------------------------------------------------------
# Point this to any saved txt table generated by the data script.
TABLE_FILE = (
    pathlib.Path(__file__).resolve().parents[2]
    / "Plots"
    / "Atmospheric test"
    / "Teff_study"
    / "r_at_beta1"
    / "hot_jupiter_r_beta1"
    / "HI_r_beta1.txt"
)

# These are generic plotting defaults. Change anything here if you want a
# different visual style without touching the saved data table.
PLOT_OVERRIDES: Dict[str, Any] = {
    "figsize": (8.5, 5.5),
    "font_sizes": {
        "font.size": 13,
        "axes.labelsize": 14,
        "axes.titlesize": 15,
        "legend.fontsize": 12,
        "xtick.labelsize": 12,
        "ytick.labelsize": 12,
    },
    "x_scale": "log",
    "y_scale": "log",
    "x_divide_by": 1e4,
    "x_label": r"Stellar $T_{\rm eff}$ [$10^4$ K]",
    "y_label": r"$r_{\beta=1} / R_{\rm p}$",
    "title_template": "{planet}: {species} at multiple orbital distances",
    "legend_title": "Distance",
    "line_colormap": "viridis",
    "line_alpha": 0.9,
    "marker": "o",
    "marker_size": 3.5,
    "line_width": 1.6,
    "grid": True,
    "grid_alpha": 0.3,
    "tight_layout": True,
    "x_ticks": [0.26, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 2, 3, 4, 5],
    "x_tick_labels": ["0.26", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1", "2", "3", "4", "5"],
    "xlim": (0.26, 5.0),
}

SAVE_PDF = True
SHOW_PLOT = True

plot_txt.SAVE_PDF = SAVE_PDF
plot_txt.SHOW_PLOT = SHOW_PLOT


def main() -> None:
    if not TABLE_FILE.exists():
        raise FileNotFoundError(f"Table file does not exist: {TABLE_FILE}")

    pdf_path = plot_txt.plot_table(TABLE_FILE, overrides=PLOT_OVERRIDES)
    print(f"Read table: {TABLE_FILE}")
    if SAVE_PDF:
        print(f"Saved plot: {pdf_path}")


if __name__ == "__main__":
    main()
